//当前元素
$(this);
//所有标签为p的元素
$("p");
//所有id为intro的元素
$("#intro");
//所有类别为intro的元素
$(".intro");
//类别为intro的<p>元素
$("p.intro")
//带有href属性的元素
$("[href]")
//选取带有href值等于#的元素
$("[href='#']")
//选取带有href值不等于#的元素
$("[href!='#']")
//选取带有href值得以.jpg结尾的元素
$("[href$='.jpg']")
//选取id=intro的<div>中类别为head的元素
$("div#intro.head")