//jQuery基本语法
$(selector).action();
//隐藏当前html
$(this).hide();
//隐藏id为text的html
$("#text").hide();
//隐藏class为text的html
$(".text").hide();
//隐藏标签为p的html
$("p").hide();
//文档就绪函数
$(document).ready(function(){
    //jQuery操作
})