//点击按钮隐藏标签为<p>的元素
$(document).ready(function(){
    $("button").click(function(){
        $("p").hide();
    })
})
//将函数绑定到文档的就绪事件中
$(document).ready(function(){})
//触发或绑定函数到被选元素的单击事件
$(selector).click(function(){})
//触发或绑定函数到被选元素的双击事件
$(selector).dblclick(function(){})
//触发或绑定函数到被选元素的获得焦点事件
$(selector).focus(function(){})
//触发或绑定函数到被选元素的鼠标悬停事件
$(selector).mouseover(function(){})